name: Signature

on:
    issues:
        types:
            - opened

permissions:
    contents: read
    issues: write

jobs:

    process_signature:
        name: process-signature
        runs-on: ubuntu-latest
        if: ${{ github.repository_owner == 'thousandbrainsproject' }}
        steps:
            - name: Checkout cla repository for actions
              uses: actions/checkout@v4
            - name: Verify credentials are set
              id: verify-credentials
              uses: actions/github-script@v7
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.CLA_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.CLA_SECRET_ACCESS_KEY }}
              with:
                script: |
                    const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
                    if (!AWS_ACCESS_KEY_ID)
                    {
                        core.setFailed("Missing CLA_ACCESS_KEY_ID secret");
                        return;
                    }
                    const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
                    if (!AWS_SECRET_ACCESS_KEY)
                    {
                        core.setFailed("Missing CLA_SECRET_ACCESS_KEY secret");
                        return;
                    }
            - name: Verify signature
              id: verify-signature
              uses: actions/github-script@v7
              with:
                script: |
                    const expectedSignatureTitle = "Contributor License Agreement v1 Signature";
                    const expectedSignatureBodyLine0 = "### CLA v1 Signature";
                    const expectedSignatureBodyLine1 = "I have read the Contributor License Agreement v1 and I hereby sign the Contributor License Agreement v1.";
                    const expectedLabel = "signature CLA v1";

                    const body = context.payload.issue.body;
                    const title = context.payload.issue.title;
                    const labels = context.payload.issue.labels;

                    if (title !== expectedSignatureTitle)
                    {
                        core.setFailed("Expected signature title not found in issue title");
                        return;
                    }

                    const lines = body.split("\n").map(line => line.trim()).filter(line => line.length > 0);
                    if (lines[0] !== expectedSignatureBodyLine0)
                    {
                        core.setFailed("Expected signature not found in issue body");
                        return;
                    }
                    if (lines[1] !== expectedSignatureBodyLine1)
                    {
                        core.setFailed("Expected signature not found in issue body");
                        return;
                    }

                    if (labels.length != 1)
                    {
                        core.setFailed("Expected exactly one label");
                        return;
                    }
                    if (labels[0].name !== expectedLabel)
                    {
                        core.setFailed("Expected label not found");
                        return;
                    }
            - name: Handle signature verification failure
              uses: actions/github-script@v7
              if: ${{ failure() && steps.verify-signature.outcome == 'failure' }}
              with:
                script: |
                    const commentBody = "> [!WARNING]\n> Signature verification failed.\n\nPlease sign the CLA by [creating a new issue](https://github.com/thousandbrainsproject/cla/issues/new?template=01_sign_cla.yml&labels=signature+CLA+v1&title=Contributor+License+Agreement+v1+Signature) and only enter the required text into the issue body.";
                    await github.rest.issues.createComment(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            body: commentBody
                        }
                    );
                    await github.rest.issues.update(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            state: "closed"
                        }
                    );
                    await github.rest.issues.lock(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            lock_reason: "resolved"
                        }
                    );
            - name: Check if already a CLA signatory
              id: check-if-already-a-cla-signatory
              uses: ./.github/actions/check_if_cla_signatory
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.CLA_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.CLA_SECRET_ACCESS_KEY }}
              with:
                cla-signatories-table-name: DynamoDB-CLASignatoriesTable-12GCQ0F0TB473
                cla-signatories-table-region: us-east-2
                cla-signatory: ${{ github.event.issue.user.login }}
            - name: Handle already a CLA signatory
              id: handle-already-a-cla-signatory
              uses: actions/github-script@v7
              if: ${{ steps.check-if-already-a-cla-signatory.outputs.result == 'already-a-signatory' }}
              with:
                script: |
                    const commentBody = "> [!WARNING]\n> You are already a CLA signatory.\n\nThank you for signing the CLA. You already signed previously.";
                    await github.rest.issues.createComment(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            body: commentBody
                        }
                    );
                    await github.rest.issues.update(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            state: "closed"
                        }
                    );
                    await github.rest.issues.lock(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            lock_reason: "resolved"
                        }
                    );
            - name: Add to CLA signatories
              id: add-to-cla-signatories
              uses: ./.github/actions/add_to_cla_signatories
              if: ${{ steps.check-if-already-a-cla-signatory.outputs.result != 'already-a-signatory' }}
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.CLA_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.CLA_SECRET_ACCESS_KEY }}
              with:
                cla-signatories-table-name: DynamoDB-CLASignatoriesTable-12GCQ0F0TB473
                cla-signatories-table-region: us-east-2
                cla-signatory: ${{ github.event.issue.user.login }}
            - name: Notify of successful signature
              id: notify-of-successful-signature
              uses: actions/github-script@v7
              if: ${{ steps.add-to-cla-signatories.outcome == 'success' }}
              with:
                script: |
                    const commentBody = "Signature verified.\n\nThank you for signing the CLA.";
                    await github.rest.issues.createComment(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            body: commentBody
                        }
                    );
                    await github.rest.issues.update(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            state: "closed"
                        }
                    );
                    await github.rest.issues.lock(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            lock_reason: "resolved"
                        }
                    );
            - name: Generate backup artifact
              id: generate-backup-artifact
              uses: actions/github-script@v7
              with:
                result-encoding: string
                script: |
                    const fs = require("fs/promises");

                    const issue = await github.rest.issues.get(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number
                        }
                    );
                    const artifactName = `${context.payload.sender.login}-signature-cla-v1-${context.payload.issue.number}`;
                    const artifactPath = `${artifactName}.json`;
                    const artifactContent = JSON.stringify(issue);
                    await fs.writeFile(artifactPath, artifactContent);
                    return artifactPath;
            - name: Upload backup artifact
              # TODO: Upload the artifact to S3 archive
              uses: actions/upload-artifact@v4
              with:
                name: ${{ steps.generate-backup-artifact.outputs.result }}
                path: ${{ steps.generate-backup-artifact.outputs.result }}
            - name: Handle automation failure
              uses: actions/github-script@v7
              if: ${{ failure() && (steps.verify-credentials.outcome == 'failure' || steps.handle-already-a-cla-signatory.outcome == 'failure' || steps.add-to-cla-signatories.outcome == 'failure' || steps.notify-of-successful-signature.outcome == 'failure') }}
              with:
                script: |
                    const commentBody = "> [!CAUTION]\n> Automation failed.\n\nPlease notify one of the [project maintainers](https://github.com/thousandbrainsproject/tbp.monty/blob/main/MAINTAINERS.md).";
                    await github.rest.issues.createComment(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            body: commentBody
                        }
                    );
                    await github.rest.issues.update(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            state: "closed"
                        }
                    );
                    await github.rest.issues.lock(
                        {
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            lock_reason: "resolved"
                        }
                    );